// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHJvwEZ9wnofcdYt4nw2-q0XsCONIV0M',
    appId: '1:390986779944:web:fa058e5b99daad9e4e141d',
    messagingSenderId: '390986779944',
    projectId: 'hotel-management-quizplus',
    authDomain: 'hotel-management-quizplus.firebaseapp.com',
    storageBucket: 'hotel-management-quizplus.appspot.com',
    measurementId: 'G-E9XMQBM290',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXRI15bra8b3NK_ipPJqF_Mbi2QgWVH3E',
    appId: '1:390986779944:android:07cf2966a186fb5c4e141d',
    messagingSenderId: '390986779944',
    projectId: 'hotel-management-quizplus',
    storageBucket: 'hotel-management-quizplus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIZg66WESOGkmHL9zJMwSNM-rfCwTSOPs',
    appId: '1:390986779944:ios:626551cabfa504674e141d',
    messagingSenderId: '390986779944',
    projectId: 'hotel-management-quizplus',
    storageBucket: 'hotel-management-quizplus.appspot.com',
    androidClientId: '390986779944-2a9r6sajv63esl5t5lg93uuel34tgskc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelManagment',
  );
}
